[package]
name = "smart_rte_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3"
smart_rte_core = { path = "../smart_rte_core" }

[dev-dependencies]
wasm-bindgen-test = "0.3"


