name: example_app
description: Example Flutter app using smartrte_flutter
version: 0.1.0
publish_to: "none"
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  smartrte_flutter:
    path: ../smartrte_flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
